#pragma once

#define MAX_FRAME_RATE 400
#define CONSOLE_EXIT_KEY 'q'
#define CONSOLE_JUMP_KEY ' '
#define TREE_SYMBOL 'T'
#define DINO_SYMBOL 'x'
#define BLANK_SYMBOL '-'
#define INITAL_PADDING 2

#define PLAY_AREA_SIZE  22
#define MAX_TREE_DISTANCE  5
#define FRAME_RATE_REDUCTION 50
#define LEVEL_UP_FACTOR  3

#define PLAYER_START_POSITION 0
#define PLAYER_SPEED 1
#define PLAYER_JUMP_SPAN 3

